#!/usr/bin/env python3
"""Copy the allowlisted browser files into public/ and write public-receipt.json.

Only the files in ALLOWLIST are published. The build refuses symlinks, files
that resolve outside the project, module imports that are not allowlisted,
and an existing public/ that it did not create. Standard library only.

Usage: python3 build_public.py
"""
import hashlib, json, os, re, shutil, sys, tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT_NAME, RECEIPT_NAME, MARKER = 'public', 'public-receipt.json', '.move-public-build'

ALLOWLIST = (
    'LICENSE', 'index.html', 'style.css',
    'app.mjs', 'clay.mjs', 'collision.mjs', 'controls.mjs', 'door-kinematics.mjs', 'door-label.mjs', 'doors.mjs',
    'furniture.mjs', 'i18n.mjs', 'layout.mjs', 'levels.mjs', 'localize-ui.mjs', 'room-picker.mjs',
    'rooms.mjs', 'imported-room.mjs', 'rounded.mjs', 'share-client.mjs', 'telemetry.mjs',
    'assets/playcanvas.min.js', 'assets/PLAYCANVAS-LICENSE.txt',
    'assets/room.glb', 'assets/room.json', 'assets/clay-normal.png', 'assets/preview.png', 'assets/og.png',
)

IMPORT_RE = re.compile(r"""(?:\bfrom\s*|\bimport\s*\(?\s*)['"](\.{1,2}/[^'"]+)['"]""")
LOCAL_REF_RE = re.compile(r"""\b(?:src|href|content)="([^"#?:]+\.(?:css|mjs|js|png|json|glb))\"""")


class BuildError(Exception):
    pass


def checked_source(root, name):
    """Return the real path of an allowlisted file, refusing symlinks and escapes."""
    path = root / name
    for parent in [path, *path.parents]:
        if parent == root: break
        if parent.is_symlink(): raise BuildError(f'symlink refused: {parent.relative_to(root)}')
    if not path.is_file(): raise BuildError(f'missing allowlisted file: {name}')
    real = path.resolve()
    if not real.is_relative_to(root.resolve()): raise BuildError(f'outside project: {name}')
    return real


def check_references(root, allowed):
    for name in allowed:
        if name.endswith('.mjs'):
            text = (root / name).read_text(encoding='utf-8')
            for ref in IMPORT_RE.findall(text):
                target = os.path.normpath(os.path.join(os.path.dirname(name), ref)).replace(os.sep, '/')
                if target not in allowed: raise BuildError(f'{name} imports non-allowlisted {ref}')
    html = (root / 'index.html').read_text(encoding='utf-8')
    for ref in LOCAL_REF_RE.findall(html):
        if ref not in allowed: raise BuildError(f'index.html references non-allowlisted {ref}')


def prepare_out(root):
    out = root / OUT_NAME
    if out.is_symlink(): raise BuildError(f'{OUT_NAME}/ is a symlink; refusing to replace it')
    if out.exists():
        if not out.is_dir() or not ((out / MARKER).is_file() or not any(out.iterdir())):
            raise BuildError(f'{OUT_NAME}/ exists and was not created by this build; move it away first')
    return out


def build(root=ROOT):
    root = Path(root).resolve()
    allowed = set(ALLOWLIST)
    sources = {name: checked_source(root, name) for name in ALLOWLIST}
    check_references(root, allowed)
    out = prepare_out(root)
    staging = Path(tempfile.mkdtemp(prefix='.public-staging-', dir=root))
    try:
        files = {}
        for name, source in sorted(sources.items()):
            data = source.read_bytes()
            target = staging / name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
            files[name] = hashlib.sha256(data).hexdigest()
        (staging / MARKER).write_text('Generated by build_public.py; safe to delete.\n')
        staging.chmod(0o755)
        if out.exists(): shutil.rmtree(out)
        staging.rename(out)
    finally:
        if staging.exists(): shutil.rmtree(staging)
    receipt = {'generator': 'build_public.py', 'root': OUT_NAME, 'files': files}
    (root / RECEIPT_NAME).write_text(json.dumps(receipt, indent=1, sort_keys=True) + '\n')
    return receipt


def main():
    try:
        receipt = build()
    except BuildError as e:
        print(f'build_public: {e}', file=sys.stderr); return 1
    print(f'{OUT_NAME}/: {len(receipt["files"])} files; receipt {RECEIPT_NAME}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
