import imported from './imported-room.mjs';
// Public export: exactly one invented room generated by scripts/generate-demo.py.
// The live site's prepared homes are not part of this repository.
export const DEFAULT_ROOM='practice-room';
// Furniture centres may move anywhere over the 5.6 m x 4.0 m synthetic floor.
export const DEFAULT_BOUNDS={min:[-2.8,0,-2],max:[2.8,2.5,2]};
const STORAGE_PREFIX='move-demo:';
const CONFIG={assetBase:'assets/room',bounds:DEFAULT_BOUNDS,center:[0,.5,0],minDistance:2.5,maxDistance:20,plinth:[6.2,.3,4.6],synthetic:true};
// Missing or default room resolves to the practice room; anything else is rejected.
export function resolveRoom(value){if(imported){if(value===undefined||value===null||value===''||value===imported.id)return imported.id;throw Error('Unknown imported room');}if(value===undefined||value===null||value===''||value===DEFAULT_ROOM)return DEFAULT_ROOM;throw Error('Unknown room');}
export function roomConfig(room){if(imported){resolveRoom(room);return imported;}if(resolveRoom(room)!==DEFAULT_ROOM)throw Error('Unknown room');return CONFIG;}
export function layoutKey(room){return STORAGE_PREFIX+'layout:'+resolveRoom(room);}
// Distance at which a sphere around the bounds fits the narrower field of view.
export function fitDistance(config,aspect,horizontalFov,fov){
 const {min,max}=config.bounds,radius=Math.hypot(...min.map((v,i)=>(max[i]-v)/2));
 const half=fov*Math.PI/360,ratio=Number.isFinite(aspect)&&aspect>0?aspect:1;
 const otherHalf=horizontalFov?Math.atan(Math.tan(half)/ratio):Math.atan(Math.tan(half)*ratio);
 const distance=radius/Math.sin(Math.min(half,otherHalf));
 return Math.max(config.minDistance,Math.min(config.maxDistance,distance));
}
