import {locales} from './i18n.mjs';
import imported from './imported-room.mjs';
import {DEFAULT_ROOM} from './rooms.mjs';
// The public export ships one invented room, so the picker explains that instead of listing homes.
export const PICKER_TEXT={
 button:['关于房间','關於房間','この部屋について','방 정보','About this room','Sobre la habitación'],
 title:['公开演示房间','公開示範房間','公開デモの部屋','공개 데모 방','Public demo room','Habitación de demostración'],
 note:['这个公开版本只包含一个虚构的练习房间，由脚本生成，不是真实住宅。原网站上的房屋模型不在其中。','這個公開版本只包含一個虛構的練習房間，由腳本生成，不是真實住宅。原網站上的房屋模型不在其中。','この公開版には、スクリプトで生成した架空の練習用の部屋が1つだけ含まれています。実在の住宅ではありません。元のサイトの住宅モデルは含まれていません。','이 공개 버전에는 스크립트로 생성한 가상의 연습용 방 하나만 들어 있습니다. 실제 집이 아니며, 원래 사이트의 집 모델은 포함되지 않습니다.','This public version contains one invented practice room generated by a script. It is not a real home, and the original site’s home models are not included.','Esta versión pública incluye una sola habitación de práctica inventada, generada por un script. No es una vivienda real y no incluye los modelos de viviendas del sitio original.'],
 name:['合成练习房间','合成練習房間','合成の練習用ルーム','합성 연습용 방','Synthetic practice room','Habitación sintética de práctica'],
 detail:['虚构 · 5.6 × 4.0 m · 无门 · 单层','虛構 · 5.6 × 4.0 m · 無門 · 單層','架空 · 5.6 × 4.0 m · ドアなし · 1フロア','가상 · 5.6 × 4.0 m · 문 없음 · 단층','Invented · 5.6 × 4.0 m · no doors · one level','Inventada · 5,6 × 4,0 m · sin puertas · una planta'],
 close:['关闭','關閉','閉じる','닫기','Close','Cerrar'],
};
const importedNotes={fictional:['虚构房间 · 尺寸仅供演示','虛構房間 · 尺寸僅供示範','架空の部屋 · 寸法はデモ用','가상의 방 · 시연용 치수','Fictional room · demonstration dimensions','Habitación ficticia · dimensiones de demostración'],estimated:['尺寸为估算 · 请对照原视频检查','尺寸為估算 · 請對照原影片檢查','推定寸法 · 元の映像と照合してください','추정 치수 · 원본 영상과 비교하세요','Estimated dimensions · check against the source video','Dimensiones estimadas · comprobar con el vídeo original']};
const text=(key,locale)=>PICKER_TEXT[key][Math.max(0,locales.indexOf(locale))];
export function setupRoomPicker(roomID,getLocale){
 const dialog=document.querySelector('#room-picker'),button=document.querySelector('#choose-room');
 const card=document.createElement('button');card.type='button';card.className='room-card';if(roomID===DEFAULT_ROOM)card.setAttribute('aria-current','page');
 const image=document.createElement('img');image.src='assets/preview.png';image.alt='';image.width=640;image.height=360;
 const name=document.createElement('strong'),detail=document.createElement('span');card.append(image,name,detail);card.onclick=()=>dialog.close();
 dialog.querySelector('.room-filters').hidden=true;dialog.querySelector('.room-grid').replaceChildren(card);
 dialog.querySelector('.room-close').onclick=()=>dialog.close();
 button.onclick=()=>dialog.showModal();
 function refresh(){
  const locale=getLocale();
  button.textContent=text('button',locale);dialog.querySelector('#room-picker-title').textContent=text('title',locale);
  dialog.querySelector('.room-note').textContent=text('note',locale);dialog.querySelector('.room-close').setAttribute('aria-label',text('close',locale));
  name.textContent=text('name',locale);detail.textContent=text('detail',locale);
  if(imported){image.hidden=true;dialog.querySelector('#room-picker-title').textContent=text('button',locale);name.textContent=imported.title;const note=importedNotes[imported.synthetic?'fictional':'estimated'][Math.max(0,locales.indexOf(locale))];dialog.querySelector('.room-note').textContent=note;detail.textContent=note;}
 }
 refresh();return refresh;
}
